name: ins0mniaque
version: 0.0.1
schema: v1

rules:
  - Please provide concise answers. Don't explain obvious concepts. You can assume that I am knowledgeable about most programming topics.

models:
  - name: Ollama
    provider: ollama
    model: AUTODETECT

  - name: qwen2.5-coder:14b
    provider: ollama
    model: qwen2.5-coder:14b
    roles:
      - chat
      - edit
      - apply

  - name: qwen2.5-coder:7b-base
    provider: ollama
    model: qwen2.5-coder:7b-base
    roles:
      - autocomplete

  - name: qwen2.5-coder:3b-base
    provider: ollama
    model: qwen2.5-coder:3b-base
    roles:
      - autocomplete

  - name: qwen2.5-coder:1.5b-base
    provider: ollama
    model: qwen2.5-coder:1.5b-base
    roles:
      - autocomplete

  - name: qwen2.5-coder:0.5b-base
    provider: ollama
    model: qwen2.5-coder:0.5b-base
    roles:
      - autocomplete

  - name: nomic-embed-text
    provider: ollama
    model: nomic-embed-text
    roles:
      - embed

  # llama-server --hf-repo klnstpr/bge-reranker-v2-m3-Q8_0-GGUF --hf-file bge-reranker-v2-m3-q8_0.gguf --port 11435 --reranking --pooling rank
  - name: bge-reranker-v2-m3
    provider: huggingface-tei
    apiBase: http://localhost:11435
    model: bge-reranker-v2-m3
    roles:
      - rerank

mcpServers:
  - name: mcp-server-fetch
    command: uvx
    args:
      - mcp-server-fetch

context:
  - provider: code
  - provider: codebase
  - provider: docs
  - provider: diff
  - provider: folder
  - provider: problems
  - provider: terminal