#!/usr/bin/env bash

micro -plugin install bounce
micro -plugin install editorconfig
micro -plugin install filemanager
micro -plugin install fish
micro -plugin install fzf
micro -plugin install go
micro -plugin install jump
micro -plugin install manipulator
micro -plugin install quickfix