# Environment
source "${XDG_CONFIG_HOME:-~/.config}"/env

# Aliases
source "${XDG_CONFIG_HOME:-~/.config}"/aliases

# Key bindings
source "/opt/homebrew/opt/fzf/shell/key-bindings.bash"

# Auto-completion
[[ $- == *i* ]] && source "/opt/homebrew/opt/fzf/shell/completion.bash" 2> /dev/null

# Configure dotnet completion
function _dotnet_bash_complete()
{
    local word="${COMP_WORDS[COMP_CWORD]}" IFS=$'\n'
    local candidates

    read -d '' -ra candidates < <(dotnet complete --position "${COMP_POINT}" "${COMP_LINE}" 2>/dev/null)
    read -d '' -ra COMPREPLY < <(compgen -W "${candidates[*]:-}" -- "$word")
}

complete -f -F _dotnet_bash_complete dotnet

# Configure zoxide
eval "$(zoxide init bash --cmd j)"

# Configure fzf
if [[ ! "$PATH" == */opt/homebrew/opt/fzf/bin* ]]; then
    export PATH="${PATH:+${PATH}:}/opt/homebrew/opt/fzf/bin"
fi

# Configure Starship
export STARSHIP_CONFIG=~/.config/starship/starship.toml
eval "$(starship init bash)"