#!/bin/bash

if [[ -z $TMUX_SEGMENTS_ASCII_MODE ]]; then
    tmux set-environment -g TMUX_SEGMENTS_ASCII_MODE 1
    tmux refresh-client -S
    tmux display "ASCII mode enabled"
else
    tmux set-environment -gu TMUX_SEGMENTS_ASCII_MODE
    tmux refresh-client -S
    tmux display "ASCII mode disabled"
fi