#!/bin/sh

print_battery()
{
    if   [ -z "$1" ];     then printf '#[fg=colour255]█'
    elif [ "$1" -ge 95 ]; then printf '#[fg=colour82]█'
    elif [ "$1" -ge 80 ]; then printf '#[fg=colour154]▇'
    elif [ "$1" -ge 65 ]; then printf '#[fg=colour226]▆'
    elif [ "$1" -ge 50 ]; then printf '#[fg=colour220]▅'
    elif [ "$1" -ge 35 ]; then printf '#[fg=colour214]▄'
    elif [ "$1" -ge 20 ]; then printf '#[fg=colour208]▃'
    elif [ "$1" -gt 5 ];  then printf '#[fg=colour202]▂'
    else                       printf '#[fg=colour160]▁'
    fi

    case $2 in
        *charged*|*full*) printf '#[fg=colour250]' ;;
        *discharging*)    printf '#[fg=colour250]' ;;
        *charging*)       printf '#[fg=colour82]'  ;;
        *attached*)       printf '#[fg=colour255]' ;;
        *)                printf '#[fg=colour250]' ;;
    esac

    printf " $1%%"
}

case $(uname -a) in
    *Microsoft*|*microsoft*)
        percentage=$(find /sys/class/power_supply/*/capacity | tail -n1 | sed -e 's/%//')
        status=$(find /sys/class/power_supply/*/status | tail -n1 | awk '{print tolower($0);}')

        print_battery "$percentage" "$status"
        exit ;;
esac

if command -v pmset > /dev/null; then
    battery=$(pmset -g batt)
    percentage=$(echo "$battery" | grep -o "[0-9]\{1,3\}%" | sed -e 's/%//')
    status=$(echo "$battery" | awk -F '; *' 'NR==2 { print $2 }')
elif command -v acpi > /dev/null; then
    battery=$(acpi -b)
    percentage=$(echo "$battery" | grep -m 1 -Eo "[0-9]+%" | sed -e 's/%//')
    status=$(echo "$battery" | awk '{gsub(/,/, ""); print tolower($3); exit}')
elif command -v apm > /dev/null; then
    percentage=$(apm -l | sed -e 's/%//')
    case $(apm -a) in
        0) status="discharging" ;;
        1) status="charging" ;;
    esac
elif command -v upower > /dev/null; then
    device=$(upower -e | grep -E 'battery|DisplayDevice'| tail -n1)
    if [ -z "$device" ]; then
        exit 1
    fi

    battery=$(upower -i "$device")
    percentage=$(echo "$battery" | awk '/percentage:/ {print $2}' | sed -e 's/%//')
    status=$(echo "$battery" | awk '/state/ {print $2}')
else
    exit 1
fi

print_battery "$percentage" "$status"