#!/bin/sh

if [ -z "$TMUX_SEGMENTS_ASCII_MODE" ]; then DOCKER_ICON=" 🐳";
else                                        DOCKER_ICON="#[fg=colour33] D#[fg=default]";
fi

if DOCKER_PS=$(docker ps 2> /dev/null); then
    echo "$DOCKER_ICON $(echo "$DOCKER_PS" | tail -n +2 | wc -l | tr -d ' ')"
fi