#!/bin/bash

COLUMNS=$(tput cols)

BOLD=$(tput bold)
TITLE=$(tput setaf 141)
KEY=$(tput setaf 229)
REPEAT=$(tput setaf 208)
OPERATOR=$(tput setaf 120)
NORMAL=$(echo -e "\033[0m")

parse_command='
{
    command   = $1;
    shortname = "";

    if(substr($2, 1, 1) == "(")
    {
        shortname = $2;
        $2="";
    }

    $1="";

    sub(/^[ ]+/, "");

    print "  ⒦" command shortname "⒩\t" $0
}'

codes='🔴🟠🟡🟢🔵🟣🟤'

highlight_command="
s/@F/🔴/g;
s/@D/🟡/g;
s/&@/${OPERATOR}>_ $NORMAL/g;
s/@%/${OPERATOR}if $NORMAL/g;
s/%@/$BOLD${OPERATOR}☰ $NORMAL/g;

s/⒦/$BOLD$KEY/g;
s/⒭/$NORMAL$REPEAT*/g;
s/⒩/$NORMAL/g;
"

parse_key_binding='
{
    key    = $4;
    repeat = "";

    if($2 == "-r")
    {
        repeat = "⒭";
        key=$5;
        $5="";
    }

    $1=""; $2=""; $3=""; $4="";

    sub(/^\"/, "", key);
    sub(/\"$/, "", key);
    sub(/^\\/, "", key);

    sub(/^[ ]+/, "");
    sub(/ \\; /, "; ");
    sub(/(send-keys|send)( -[MNX])* /, "@\\&");
    sub(/command-prompt( -?[0-NPpiI])* /, "\\&@");
    sub(/(if-shell|if)( -F)?( -t [^[:space:]])? /, "@%");
    sub(/display-menu( -T \"[^\"]+\")?( -t [^[:space:]])?( -x)?( [^[:space:]] -y)? /, "%@");

    print "  ⒦" key repeat "⒩\t" $0
}'

highlight_key_binding="
s/@&/${OPERATOR}⮕ $NORMAL/g;
s/&@/${OPERATOR}>_ $NORMAL/g;
s/@%/${OPERATOR}if $NORMAL/g;
s/%@/$BOLD${OPERATOR}☰ $NORMAL/g;

s/⒦/$BOLD$KEY/g;
s/⒭/$NORMAL$REPEAT*/g;
s/⒩/$NORMAL/g;
"

list_commands () {
  tmux list-commands | awk "$parse_command"
}

list_table_shortcuts () {
  tmux list-keys -T $1 | sed "s/${HOME//\//\\/}/~/" | awk "$parse_key_binding"
}

print_commands () {
echo $BOLD$TITLE$1$NORMAL
printf "$BOLD$TITLE%${#1}s\n$NORMAL" "" | tr ' ' '‾'
list_commands | sed "$highlight_command"
echo ""
}

print_table_shortcuts () {
echo $BOLD$TITLE$1$NORMAL
printf "$BOLD$TITLE%${#1}s\n$NORMAL" "" | tr ' ' '‾'
list_table_shortcuts $2 | sed "$highlight_key_binding"
echo ""
}

print_commands "Commands"

print_table_shortcuts "Global shortcuts"       root
print_table_shortcuts "Prefix shortcuts"       prefix
print_table_shortcuts "Copy mode shortcuts"    copy-mode
print_table_shortcuts "Vi copy mode shortcuts" copy-mode-vi