#!/bin/sh

if [ -z "$TMUX_SEGMENTS_ASCII_MODE" ]; then LAN_ICON=" 🄻 ";
else                                        LAN_ICON=" L ";
fi

interfaces=$(ifconfig 2>/dev/null | awk -F':' '/^[a-z]/ && !/^(lo|ppp|tun|utun)/ { print $1 }')
for interface in $interfaces; do
    LAN_IP="$LAN_IP$(ifconfig "${interface}" 2>/dev/null | awk '$1 == "inet" { gsub(/^192\.168\.|^10\./, ".", $2); print $2" " }')"
done

if [ -n "$LAN_IP" ]; then
    echo "#[fg=colour33]$LAN_ICON#[fg=colour39]$LAN_IP"
fi