#!/bin/sh

if [ -z "$TMUX_SEGMENTS_ASCII_MODE" ]; then VPN_ICON=" 🅅 ";
else                                        VPN_ICON=" V ";
fi

interfaces=$(ifconfig 2>/dev/null | awk -F':' '/^(ppp|tun|utun)/ { print $1 }')
for interface in $interfaces; do
    VPN_IP="$VPN_IP$(ifconfig "${interface}" 2>/dev/null | awk '$1 == "inet" { gsub(/^192\.168\./, ".", $2); print $2" " }')"
done

if [ -n "$VPN_IP" ]; then
    echo "#[fg=colour162]$VPN_ICON#[fg=colour205]$VPN_IP"
else
    exit 1
fi