# Layout

add_newline = false
format = "\u001b7$fill$shell$all\u001b8$directory$character"

[fill]
symbol = " "

[line_break]
disabled = true

# Battery

[battery]
disabled = true

# Directory

[directory]
repo_root_style = "bold purple"
truncation_length = 8
truncation_symbol = "…/"

[shell]
disabled = false

[shlvl]
disabled = false
symbol = "^"

# Unicode symbols

[erlang]
symbol = "℮ "

[git_branch]
symbol = "⎇ "

[hg_branch]
symbol = "⎇ "

[nodejs]
symbol = "⬢(green) "

[pulumi]
symbol = "🎲 "